Repository BarcelonaTC/Qurio, pull requests merged in 2025-10, with the labels that each got.

#17 Feature/splash screen
  .github/workflows/branch-name-checking-ci.yml
  .github/workflows/build-ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/barcelona/qurio/MainActivity.kt
  app/src/main/res/drawable/logo_inset.xml
  app/src/main/res/drawable/splash_logo.png
  app/src/main/res/layout/difficulty_level_button.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: feature

#19 Feature/base fragment
  app/build.gradle.kts
  app/src/main/java/com/barcelona/qurio/view/BaseFragment.kt
Labels: base

#31 Component/button
  app/build.gradle.kts
  app/src/main/java/com/barcelona/qurio/customView/ButtonShapeView.kt
  app/src/main/java/com/barcelona/qurio/customView/PlayButton.kt
  app/src/main/java/com/barcelona/qurio/customView/SecondaryButton.kt
  app/src/main/java/com/barcelona/qurio/customView/TextButton.kt
  app/src/main/res/color/text_button_color.xml
  app/src/main/res/components/layout/day_item.xml
  app/src/main/res/components/layout/difficulty_level_button.xml
  app/src/main/res/components/layout/general_top_bar.xml
  app/src/main/res/components/layout/home_top_bar.xml
  app/src/main/res/components/layout/play_button.xml
  app/src/main/res/components/layout/result_item.xml
  app/src/main/res/components/layout/streak_item.xml
  app/src/main/res/drawable/secondary_button_bg.xml
  app/src/main/res/drawable/star.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/secondary_button.xml
  app/src/main/res/layout/text_button.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: component

#33 feat: Add PlayButton custom view
  app/src/main/java/com/barcelona/qurio/customView/PrimaryButton.kt
  app/src/main/res/color/primary_button_text_color.xml
  app/src/main/res/components/layout/primary_button.xml
  app/src/main/res/components/layout/secondary_button.xml
  app/src/main/res/components/layout/text_button.xml
  app/src/main/res/drawable/primary_button_bg.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: component

#34 Add question card and text layouts with styles
  app/src/main/res/drawable/planet_dessert.png
  app/src/main/res/drawable/question_card.xml
  app/src/main/res/drawable/top_qes_shape.xml
  app/src/main/res/layout/question_image.xml
  app/src/main/res/layout/question_text.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: component
